name: Generate Wavetables

on:
  push:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and run
        run: |
          cargo build --release
          ./target/release/wavetable
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rich-Nested-FM
          path: Rich-Nested-FM

